Vagrant.configure("2") do |config|
		config.vm.define "xilito" do |xilito|
			xilito.vm.box = "ubuntu/focal64"
			xilito.vm.network "public_network"
			xilito.vm.provision "shell", path: "./script.sh"
					config.vm.provider "virtualbox" do |v|
						v.memory = "512"
						v.cpus = "2"
						v.name = "xilito"
					end
			end
end