Vagrant.configure("2") do |config|
	(1..2).each do |i| 
		config.vm.define "docker0#{i}" do |config|
			config.vm.box = "centos/7"
			config.vm.network "public_network", bridged: "Realtek Gaming GBE Family Controller", ip: "192.168.1.20#{i}"
			#config.vm.provision "shell", inline: <<-SHELL
			#			sudo hostnamectl set-hostname robot0#{i} && \						
			#			sudo apt update -y && \
			#			sudo curl -fsSL https://get.docker.com | bash && sudo usermod -aG docker vagrant && \            
			#			sudo apt-get update && apt-get install -y kubelet kubeadm kubectl glusterfs-server wget perl iotop net-tools htop git policycoreutils selinux-utils selinux-basics && \
			#			sudo sed -i "s/cgroup-driver=systemd/cgroup-driver=cgroupfs/g" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf && \
			#			sudo systemctl daemon-reload && systemctl enable kubelet docker && systemctl restart kubelet && \
			#			sudo service ufw stop && systemctl disable ufw && \
			#			sudo sed -i "s/SELINUX=enforcing/SELINUX=disabled/g" /etc/selinux/config && \
			#			sudo reboot					
			#			SHELL
					config.vm.provider "virtualbox" do |v|
						v.memory = "1024"
						v.cpus = "4"
						v.name = "docker0#{i}"
					end
		end
	end
end